/* Shared capture-only DOM guard, also bundled in the Simulator QA host.
 * No API calls, persistence, form edits or personal values leave this closure.
 * Unknown text is private by default. Only exact static UI labels are exposed.
 */
(() => {
  'use strict';
  if (window.__diewishEvidenceMask) return;
  const labels = new Set([
    'Diewish', 'Diewish Koç', 'Dashboard', 'Bugünkü Yolculuğum', 'Bugün için hızlı işlemler',
    'Su', 'Beslenme', 'Hareket', 'Kilo', 'Güncel kg', 'Hedef kg', 'İlerleme', 'Su Ekle',
    'Öğün Ekle', 'Hareket Ekle', 'Kilo Ekle', 'Kilo & ilerleme', 'Kan Tahlili', 'Kan Tahlilleri',
    'Kan tahlilleri', 'Besin ve Barkod Tarayıcı', 'Kan Tahlili Analizi', 'İlerlememi Gör',
    'Koç', 'Diewish Her Zaman Yanında', 'Öğün Planım', 'Beslenme Planım', 'Nutrition Plan', 'Hedefler', 'Sağlık Profilim',
    'Sağlık Verilerim', 'Sağlık Durumu', 'Beslenme Tercihi', 'Alerjiler', 'Başarılar',
    'Hesap', 'Oturum', 'Profili düzenle', 'Abonelik', 'Bildirim tercihleri', 'Bildirim Tercihleri',
    'Gizlilik ve izinler', 'Şifre değiştir', 'Çıkış yap', 'Çıkış', 'Çıkış Yap',
    'Ana Sayfa', 'Profil', 'Bildirimler', 'Yeni Sohbet', 'Yeni sohbet', 'ÖNCEKİ SOHBETLER',
    'Sohbetler', 'Sohbet geçmişi', 'Gönder', 'Kapat', 'Kaydet', 'İptal', 'Düzenle',
    'Öğün hatırlatmaları', 'Su hatırlatmaları', 'Aktivite hatırlatmaları', 'Uyku hazırlığı', 'Haftalık özet', 'Diewish Koç bildirimleri', 'Cihaz bildirimi', 'Bildirim iznini kontrol et', 'Bildirim izni ver', 'Tarayıcı bildirimlerini etkinleştir', 'Tam zamanlı hatırlatıcı izni ver', 'Anlık yerel bildirimi test et', 'Bu cihazda bildirim izni ver',
    'E-posta', 'Şifre', 'Şifremi unuttum', 'Beni hatırla', 'Giriş Yap', 'Tekrar hoş geldiniz',
    'Hesabınıza giriş yapın', 'veya', 'Google ile devam et', 'Telefon numarası ile devam et',
    'Apple ile devam et', 'Hesabın yok mu?', 'Kayıt ol', 'Hazır', 'Boş', 'kg', 'kcal', 'dk',
    'Bugün', 'Hafta', 'Ay', 'Hızlı İşlemler', 'Dashboard düzenle', 'Kartları düzenle',
  ]);
  let state = null;
  let reason = 'NONE';
  const normalized = text => text.replace(/\s+/g, ' ').trim();
  // Only a neutral marker generated by the existing sync harness is exempt.
  const publicText = text => {
    const value=normalized(text);
    const marker=value.match(/^QA-sync-[a-f0-9]{16}(.*)$/);
    return labels.has(value) || Boolean(marker && ' — Merhaba, yalnız kısa bir selamlama yanıtı ver.'.startsWith(marker[1]));
  };
  function restore() {
    if (!state) return true;
    state.observer?.disconnect();
    cancelAnimationFrame(state.frame);
    removeEventListener('resize', invalidate);
    removeEventListener('scroll', invalidate, true);
    document.fonts.removeEventListener('loading', fontsChanged);
    document.fonts.removeEventListener('loadingdone', fontsChanged);
    const restored=new Set();
    for (const [element,saved] of state.styleStates) {
      if(element.getAttribute('style')===saved.masked) {
        if(saved.original===null) element.removeAttribute('style'); else element.setAttribute('style',saved.original);
        restored.add(element);
      }
    }
    for (const edit of state.edits) {
      if(restored.has(edit.element)) continue;
      // Restore only our own temporary property; never overwrite a later app edit.
      if (edit.element.style.getPropertyValue(edit.property)===edit.masked && edit.element.style.getPropertyPriority(edit.property)==='important') {
        if(edit.value) edit.element.style.setProperty(edit.property,edit.value,edit.priority);
        else edit.element.style.removeProperty(edit.property);
      }
    }
    for(const [element,saved] of state.styleStates) if(saved.original===null && element.style.length===0) element.removeAttribute('style');
    state.host.remove(); state.style.remove(); state = null;
    return true;
  }
  function invalidate(cause) {
    if (!state || !state.ready) return;
    reason = ['VIEWPORT_CHANGED','FONT_CHANGED','DOCUMENT_MUTATION'].includes(cause) ? cause : 'DOCUMENT_MUTATION';
    state.ready = false;
    state.shield.style.display = 'block';
    try { window.webkit?.messageHandlers?.diewishIOS?.postMessage({version:1,operation:'qa-mask-invalid'}); } catch (_) {}
  }
  const fontProperties = face => [face.family,face.style,face.weight,face.stretch,face.unicodeRange,face.variant,face.featureSettings,face.status].join('|');
  function fontSetChanged() {
    const faces=[...document.fonts];
    return document.fonts.status!=='loaded' || faces.length!==state.fonts.length || faces.some((face,i)=>face!==state.fonts[i].face || fontProperties(face)!==state.fonts[i].properties);
  }
  function fontsChanged(){
    // WebKit can notify loadingdone without changing any FontFace. Such a
    // notification cannot alter pixels. Real set/status/geometry changes fail.
    if(state?.ready && (fontSetChanged() || state.checks.some(check=>geometry(check.object)!==check.geometry))) invalidate('FONT_CHANGED');
  }
  function relevant(record) {
    if (state?.host.contains(record.target)) return false;
    // WebKit screenshot plumbing adds/removes precisely this empty rule.
    // It changes no declaration, text, value or geometry. No other application
    // mutation is exempt, and geometry is checked independently below.
    const nodes=[...record.addedNodes,...record.removedNodes];
    return !(record.type==='childList' && record.target===document.head && nodes.length && nodes.every(n=>n.nodeType===1 && n.tagName==='STYLE' && n.attributes.length===0 && n.textContent==='body {}'));
  }
  const geometry = object => JSON.stringify([...object.getClientRects()].map(r=>[r.left,r.top,r.width,r.height]));
  function active() {
    if (!state || !state.ready || !state.host.isConnected || !state.style.isConnected) { if(reason==='NONE') reason='MASK_NOT_ACTIVE'; return false; }
    if (state.viewport.width !== innerWidth || state.viewport.height !== innerHeight || state.host.getBoundingClientRect().width < innerWidth || state.host.getBoundingClientRect().height < innerHeight) { invalidate('VIEWPORT_CHANGED'); return false; }
    if (fontSetChanged()) { invalidate('FONT_CHANGED'); return false; }
    if (state.observer.takeRecords().some(relevant)) { invalidate('DOCUMENT_MUTATION'); return false; }
    if (state.checks.some(check=>geometry(check.object)!==check.geometry)) { invalidate('DOCUMENT_MUTATION'); return false; }
    return true;
  }
  async function begin() {
    restore();
    reason='NONE';
    if ([...document.querySelectorAll('input[type=email],input[type=password],input[name=email],input[name=password]')].some(n => n.value)) return false;
    const host = document.createElement('div');
    host.setAttribute('data-qa-health-mask', 'HEALTH_MASK_V1');
    host.style.cssText = 'position:fixed!important;inset:0!important;width:100vw!important;height:100vh!important;z-index:2147483647!important;pointer-events:none!important;opacity:1!important;visibility:visible!important;display:block!important;transform:none!important;filter:none!important;mix-blend-mode:normal!important;isolation:isolate!important;';
    const shadow = host.attachShadow({mode:'closed'});
    const shield = document.createElement('div');
    shield.style.cssText = 'position:absolute;inset:0;background:#263b35;color:white;display:block;';
    shield.textContent = '[masked]';
    const style = document.createElement('style');
    style.textContent = '*{animation:none!important;transition:none!important;caret-color:transparent!important}';
    document.head.appendChild(style); document.documentElement.appendChild(host); shadow.appendChild(shield);
    state = {host,shield,style,ready:false,frame:0,observer:null,checks:[],edits:[],styleStates:new Map()};
    function maskStyle(element,property,masked) {
      if(!state.styleStates.has(element)) state.styleStates.set(element,{original:element.getAttribute('style'),masked:null});
      state.edits.push({element,property,masked,value:element.style.getPropertyValue(property),priority:element.style.getPropertyPriority(property)});
      element.style.setProperty(property,masked,'important');
      state.styleStates.get(element).masked=element.getAttribute('style');
      if (getComputedStyle(element).getPropertyValue(property)!==masked) throw new Error('STYLE_MASK_FAILED');
    }
    function cover(rect) {
      if (!rect || rect.width <= 0 || rect.height <= 0 || rect.bottom < 0 || rect.top > innerHeight || rect.right < 0 || rect.left > innerWidth) return;
      const block = document.createElement('div');
      // Expand over glyph antialiasing, keep the original element's layout.
      block.style.cssText = `position:absolute;left:${Math.max(0,rect.left-2)}px;top:${Math.max(0,rect.top-2)}px;width:${rect.width+4}px;height:${rect.height+4}px;overflow:hidden;background:#354b43;color:#fff;font:10px sans-serif;line-height:${rect.height+4}px;white-space:nowrap;opacity:1;`;
      block.textContent = '[masked]'; shadow.appendChild(block);
    }
    try {
      // Wait for hydration before measuring; changes DURING capture still fail.
      await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('FONT_TIMEOUT')),5000);document.fonts.ready.then(()=>{clearTimeout(timer);resolve();});});
      await new Promise((resolve,reject) => {
        let quiet;
        const observer=new MutationObserver(()=>{clearTimeout(quiet);quiet=setTimeout(done,500);});
        const limit=setTimeout(()=>{observer.disconnect();clearTimeout(quiet);reject(new Error('QUIET_TIMEOUT'));},5000);
        function done(){observer.disconnect();clearTimeout(limit);resolve();}
        observer.observe(document.documentElement,{subtree:true,childList:true,attributes:true,characterData:true});
        quiet=setTimeout(done,500);
      });
      await new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)));
      const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
      let node;
      while ((node = walker.nextNode())) {
        if (!node.textContent.trim() || node.parentElement?.closest('script,style,noscript')) continue;
        if (publicText(node.textContent) && !node.parentElement?.closest('[data-health-value],[data-personal-value]')) continue;
        const range = document.createRange(); range.selectNodeContents(node);
        [...range.getClientRects()].forEach(cover);
        state.checks.push({object:range,geometry:geometry(range)});
      }
      for (const element of document.body.querySelectorAll('*')) {
        const css = getComputedStyle(element);
        // Values can be encoded in input fields, chart pixels, images, custom
        // elements or pseudo-content. Exact static labels do not exempt these.
        const visual = element.matches('img,canvas,video,iframe,object,embed,[role=progressbar],svg:not(.lucide)') || element.shadowRoot || element.tagName.includes('-');
        const field = element.matches('textarea,select,input:not([type=checkbox]):not([type=radio]):not([type=button]):not([type=submit]):not([type=hidden])');
        const generated = ['::before','::after'].some(pseudo => { const content=getComputedStyle(element,pseudo).content; return content && !['none','normal','""',"''"].includes(content); });
        // Hide only the visual layer, so overlaid card labels stay readable.
        if (visual) maskStyle(element,'opacity','0');
        if (css.backgroundImage.includes('url(')) maskStyle(element,'background-image','none');
        if (field || generated || element.shadowRoot || element.tagName.includes('-')) cover(element.getBoundingClientRect());
        if (visual || field || generated || css.backgroundImage.includes('url(')) state.checks.push({object:element,geometry:geometry(element)});
      }
      // Painting the overlays can itself request a system font in WebKit. Settle
      // that request before arming the capture guard; never ignore font changes
      // once capture is armed. A changed private range requires a fresh attempt.
      await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('FONT_TIMEOUT')),5000);document.fonts.ready.then(()=>{clearTimeout(timer);resolve();});});
      await new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)));
      if (state.checks.some(check=>geometry(check.object)!==check.geometry)) throw new Error('GEOMETRY_CHANGED');
      // Android WebView CSS vw can be fractional while innerWidth is rounded.
      // Use an explicit covering pixel size, and separately watch the viewport.
      state.fonts=[...document.fonts].map(face=>({face,properties:fontProperties(face)}));
      state.viewport={width:innerWidth,height:innerHeight};
      host.style.setProperty('width',innerWidth+'px','important');
      host.style.setProperty('height',innerHeight+'px','important');
      state.observer = new MutationObserver(records => { if (records.some(relevant)) invalidate('DOCUMENT_MUTATION'); });
      state.observer.observe(document.documentElement,{subtree:true,childList:true,characterData:true,attributes:true});
      addEventListener('resize',invalidate); addEventListener('scroll',invalidate,true);
      document.fonts.addEventListener('loading',fontsChanged); document.fonts.addEventListener('loadingdone',fontsChanged);
      shield.style.display='none'; state.ready=true;
      const watch = () => { if (state?.ready) { active(); if (state?.ready) state.frame=requestAnimationFrame(watch); } };
      state.frame=requestAnimationFrame(watch);
      return active();
    } catch (_) { reason='PREPARE_FAILED'; restore(); return false; }
  }
  window.__diewishEvidenceMask = Object.freeze({begin,active,restore,reason:()=>reason,version:'HEALTH_MASK_V1'});
})();
