/* Shared capture-only DOM guard, also bundled in the Simulator QA host.
 * No API calls, persistence, form edits or personal values leave this closure.
 * Unknown text is private by default. Only exact static UI labels are exposed.
 */
(() => {
  'use strict';
  if (window.__diewishEvidenceMask) return;
  const labels = new Set([
    'Diewish', 'Diewish Koç', 'Dashboard', 'Bugünkü Yolculuğum', 'Bugün için hızlı işlemler',
    'Su', 'Beslenme', 'Hareket', 'Kilo', 'Güncel kg', 'Hedef kg', 'İlerleme', 'Su Ekle',
    'Öğün Ekle', 'Hareket Ekle', 'Kilo Ekle', 'Kilo & ilerleme', 'Kan Tahlili', 'Kan Tahlilleri',
    'Kan tahlilleri', 'Besin ve Barkod Tarayıcı', 'Kan Tahlili Analizi', 'İlerlememi Gör',
    'Koç', 'Öğün Planım', 'Beslenme Planım', 'Nutrition Plan', 'Hedefler', 'Sağlık Profilim',
    'Sağlık Verilerim', 'Sağlık Durumu', 'Beslenme Tercihi', 'Alerjiler', 'Başarılar',
    'Hesap', 'Oturum', 'Profili düzenle', 'Abonelik', 'Bildirim tercihleri', 'Bildirim Tercihleri',
    'Gizlilik ve izinler', 'Şifre değiştir', 'Çıkış yap', 'Çıkış', 'Çıkış Yap',
    'Ana Sayfa', 'Profil', 'Bildirimler', 'Yeni Sohbet', 'Yeni sohbet', 'ÖNCEKİ SOHBETLER',
    'Sohbetler', 'Sohbet geçmişi', 'Gönder', 'Kapat', 'Kaydet', 'İptal', 'Düzenle',
    'Öğün hatırlatmaları', 'Su hatırlatmaları', 'Bu cihazda bildirim izni ver',
    'E-posta', 'Şifre', 'Şifremi unuttum', 'Beni hatırla', 'Giriş Yap', 'Tekrar hoş geldiniz',
    'Hesabınıza giriş yapın', 'veya', 'Google ile devam et', 'Telefon numarası ile devam et',
    'Apple ile devam et', 'Hesabın yok mu?', 'Kayıt ol', 'Hazır', 'Boş', 'kg', 'kcal', 'dk',
    'Bugün', 'Hafta', 'Ay', 'Hızlı İşlemler', 'Dashboard düzenle', 'Kartları düzenle',
  ]);
  let state = null;
  const normalized = text => text.replace(/\s+/g, ' ').trim();
  // Only a neutral marker generated by the existing sync harness is exempt.
  const publicText = text => {
    const value=normalized(text);
    const marker=value.match(/^QA-sync-[a-f0-9]{16}(.*)$/);
    return labels.has(value) || Boolean(marker && ' — Merhaba, yalnız kısa bir selamlama yanıtı ver.'.startsWith(marker[1]));
  };
  function restore() {
    if (!state) return true;
    state.observer?.disconnect();
    cancelAnimationFrame(state.frame);
    removeEventListener('resize', invalidate);
    removeEventListener('scroll', invalidate, true);
    state.host.remove(); state.style.remove(); state = null;
    return true;
  }
  function invalidate() {
    if (!state || !state.ready) return;
    state.ready = false;
    state.shield.style.display = 'block';
    try { window.webkit?.messageHandlers?.diewishIOS?.postMessage({version:1,operation:'qa-mask-invalid'}); } catch (_) {}
  }
  function active() {
    if (!state || !state.ready || !state.host.isConnected || !state.style.isConnected) return false;
    if (state.host.getBoundingClientRect().width !== innerWidth || state.host.getBoundingClientRect().height !== innerHeight) { invalidate(); return false; }
    if (state.observer.takeRecords().some(record => !state.host.contains(record.target))) { invalidate(); return false; }
    return true;
  }
  async function begin() {
    restore();
    if ([...document.querySelectorAll('input[type=email],input[type=password],input[name=email],input[name=password]')].some(n => n.value)) return false;
    const host = document.createElement('div');
    host.setAttribute('data-qa-health-mask', 'HEALTH_MASK_V1');
    host.style.cssText = 'position:fixed!important;inset:0!important;width:100vw!important;height:100vh!important;z-index:2147483647!important;pointer-events:none!important;opacity:1!important;visibility:visible!important;display:block!important;transform:none!important;filter:none!important;mix-blend-mode:normal!important;isolation:isolate!important;';
    const shadow = host.attachShadow({mode:'closed'});
    const shield = document.createElement('div');
    shield.style.cssText = 'position:absolute;inset:0;background:#263b35;color:white;display:block;';
    shield.textContent = '[masked]';
    const style = document.createElement('style');
    style.textContent = '*{animation:none!important;transition:none!important;caret-color:transparent!important}';
    document.head.appendChild(style); document.documentElement.appendChild(host); shadow.appendChild(shield);
    state = {host,shield,style,ready:false,frame:0,observer:null};
    function cover(rect) {
      if (!rect || rect.width <= 0 || rect.height <= 0 || rect.bottom < 0 || rect.top > innerHeight || rect.right < 0 || rect.left > innerWidth) return;
      const block = document.createElement('div');
      // Expand over glyph antialiasing, keep the original element's layout.
      block.style.cssText = `position:absolute;left:${Math.max(0,rect.left-2)}px;top:${Math.max(0,rect.top-2)}px;width:${rect.width+4}px;height:${rect.height+4}px;overflow:hidden;background:#354b43;color:#fff;font:10px sans-serif;line-height:${rect.height+4}px;white-space:nowrap;opacity:1;`;
      block.textContent = '[masked]'; shadow.appendChild(block);
    }
    try {
      await new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)));
      const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
      let node;
      while ((node = walker.nextNode())) {
        if (!node.textContent.trim() || node.parentElement?.closest('script,style,noscript')) continue;
        if (publicText(node.textContent) && !node.parentElement?.closest('[data-health-value],[data-personal-value]')) continue;
        const range = document.createRange(); range.selectNodeContents(node);
        [...range.getClientRects()].forEach(cover);
      }
      for (const element of document.body.querySelectorAll('*')) {
        const css = getComputedStyle(element);
        // Values can be encoded in input fields, chart pixels, images, custom
        // elements or pseudo-content. Exact static labels do not exempt these.
        const visual = element.matches('img,canvas,video,iframe,object,embed,[role=progressbar],svg:not(.lucide)') || element.shadowRoot || element.tagName.includes('-');
        const field = element.matches('textarea,select,input:not([type=checkbox]):not([type=radio]):not([type=button]):not([type=submit]):not([type=hidden])');
        const generated = ['::before','::after'].some(pseudo => { const content=getComputedStyle(element,pseudo).content; return content && !['none','normal','""',"''"].includes(content); });
        if (visual || field || generated || css.backgroundImage.includes('url(')) cover(element.getBoundingClientRect());
      }
      state.observer = new MutationObserver(records => { if (records.some(record => !host.contains(record.target))) invalidate(); });
      state.observer.observe(document.documentElement,{subtree:true,childList:true,characterData:true,attributes:true});
      addEventListener('resize',invalidate); addEventListener('scroll',invalidate,true);
      shield.style.display='none'; state.ready=true;
      const watch = () => { if (state?.ready) { active(); if (state?.ready) state.frame=requestAnimationFrame(watch); } };
      state.frame=requestAnimationFrame(watch);
      return active();
    } catch (_) { restore(); return false; }
  }
  window.__diewishEvidenceMask = Object.freeze({begin,active,restore,version:'HEALTH_MASK_V1'});
})();
