CREATE TABLE "notification_preferences" (
  "id" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "mealReminders" BOOLEAN NOT NULL DEFAULT false,
  "waterReminders" BOOLEAN NOT NULL DEFAULT false,
  "activityReminders" BOOLEAN NOT NULL DEFAULT false,
  "sleepReminders" BOOLEAN NOT NULL DEFAULT false,
  "weeklySummary" BOOLEAN NOT NULL DEFAULT false,
  "coachTips" BOOLEAN NOT NULL DEFAULT false,
  "bloodTestReminders" BOOLEAN NOT NULL DEFAULT false,
  "productUpdates" BOOLEAN NOT NULL DEFAULT false,
  "waterReminderTime" TEXT NOT NULL DEFAULT '10:00',
  "activityReminderTime" TEXT NOT NULL DEFAULT '18:00',
  "sleepReminderTime" TEXT NOT NULL DEFAULT '22:30',
  "weeklySummaryDay" INTEGER NOT NULL DEFAULT 0,
  "weeklySummaryTime" TEXT NOT NULL DEFAULT '10:00',
  "timezoneOffsetMinutes" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT "notification_preferences_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "notification_preferences_userId_key" UNIQUE ("userId"),
  CONSTRAINT "notification_preferences_weekly_day_check" CHECK ("weeklySummaryDay" BETWEEN 0 AND 6),
  CONSTRAINT "notification_preferences_timezone_check" CHECK ("timezoneOffsetMinutes" BETWEEN -840 AND 840),
  CONSTRAINT "notification_preferences_water_time_check" CHECK ("waterReminderTime" ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'),
  CONSTRAINT "notification_preferences_activity_time_check" CHECK ("activityReminderTime" ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'),
  CONSTRAINT "notification_preferences_sleep_time_check" CHECK ("sleepReminderTime" ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'),
  CONSTRAINT "notification_preferences_weekly_time_check" CHECK ("weeklySummaryTime" ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'),
  CONSTRAINT "notification_preferences_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE
);
