import type { FoodCatalogItem } from "@/domain/meals/types";

/**
 * Placeholder searchable food catalog. Replaces a future backend food database.
 * Macros are per the stated serving size.
 */
export const FOOD_CATALOG: readonly FoodCatalogItem[] = [
  {
    id: "f-yumurta",
    name: "Haşlanmış Yumurta",
    serving: "1 adet (50 g)",
    calories: 78,
    protein: 6,
    carbs: 1,
    fat: 5,
  },
  {
    id: "f-yulaf",
    name: "Yulaf Ezmesi",
    serving: "40 g",
    calories: 150,
    protein: 5,
    carbs: 27,
    fat: 3,
  },
  {
    id: "f-yogurt",
    name: "Yoğurt (yağlı)",
    serving: "150 g",
    calories: 90,
    protein: 8,
    carbs: 7,
    fat: 5,
  },
  {
    id: "f-tavuk",
    name: "Izgara Tavuk Göğsü",
    serving: "100 g",
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 4,
  },
  {
    id: "f-pilav",
    name: "Pirinç Pilavı",
    serving: "150 g",
    calories: 205,
    protein: 4,
    carbs: 44,
    fat: 1,
  },
  {
    id: "f-salata",
    name: "Mevsim Salata",
    serving: "1 porsiyon",
    calories: 70,
    protein: 2,
    carbs: 9,
    fat: 3,
  },
  {
    id: "f-somon",
    name: "Fırında Somon",
    serving: "120 g",
    calories: 250,
    protein: 25,
    carbs: 0,
    fat: 16,
  },
  { id: "f-muz", name: "Muz", serving: "1 orta boy", calories: 105, protein: 1, carbs: 27, fat: 0 },
  {
    id: "f-elma",
    name: "Elma",
    serving: "1 orta boy",
    calories: 95,
    protein: 0,
    carbs: 25,
    fat: 0,
  },
  { id: "f-badem", name: "Badem", serving: "30 g", calories: 180, protein: 6, carbs: 6, fat: 15 },
  {
    id: "f-peynir",
    name: "Beyaz Peynir",
    serving: "40 g",
    calories: 110,
    protein: 7,
    carbs: 1,
    fat: 9,
  },
  {
    id: "f-ekmek",
    name: "Tam Buğday Ekmeği",
    serving: "1 dilim",
    calories: 80,
    protein: 4,
    carbs: 14,
    fat: 1,
  },
  {
    id: "f-makarna",
    name: "Tam Buğday Makarna",
    serving: "150 g",
    calories: 210,
    protein: 8,
    carbs: 42,
    fat: 2,
  },
  {
    id: "f-mercimek",
    name: "Mercimek Çorbası",
    serving: "1 kase",
    calories: 140,
    protein: 9,
    carbs: 20,
    fat: 3,
  },
  {
    id: "f-avokado",
    name: "Avokado",
    serving: "1/2 adet",
    calories: 160,
    protein: 2,
    carbs: 9,
    fat: 15,
  },
  {
    id: "f-kofte",
    name: "Izgara Köfte",
    serving: "100 g",
    calories: 240,
    protein: 18,
    carbs: 4,
    fat: 17,
  },
];
