import type { BloodTestNormalizedValue } from "@/infrastructure/tracking/blood-test-client";

/**
 * Curated second-layer education for Premium blood-test results.
 *
 * This content intentionally describes associations rather than diagnoses. A
 * low/high laboratory value can be a marker of many different situations and
 * is not necessarily the direct cause of symptoms or harm. The UI keeps this
 * material collapsed by default so the result list remains easy to scan.
 */
export interface BiomarkerDeepEducation {
  subject: string;
  whatItIs: string;
  bodyRole: string;
  lowMeaning: string;
  highMeaning: string;
  whyOutOfRangeMatters: string;
  relatedCodes: string[];
}

const DEEP: Record<string, BiomarkerDeepEducation> = {
  WBC: {
    subject: "Lökositler",
    whatItIs: "Lökositler, bağışıklık sistemini oluşturan beyaz kan hücrelerinin genel adıdır. Nötrofil, lenfosit, monosit, eozinofil ve bazofil gibi farklı hücre gruplarını kapsar.",
    bodyRole: "Mikroorganizmaların ve yabancı yapıların tanınması, bağışıklık yanıtının düzenlenmesi ve hasarlı dokuların temizlenmesi gibi savunma süreçlerine katılırlar.",
    lowMeaning: "Düşük WBC; bazı viral enfeksiyonlar, bazı ilaçlar, kemik iliği baskılanması veya başka nedenlerle ilişkili olabilir. Hangi lökosit grubunun azaldığı ayrıca önemlidir.",
    highMeaning: "Yüksek WBC; enfeksiyon, inflamasyon, fiziksel stres ve bazı ilaçlar dahil birçok durumla ilişkili olabilir. Alt hücre gruplarının dağılımı yorumu değiştirir.",
    whyOutOfRangeMatters: "Belirgin veya kalıcı değişikliklerde bağışıklık hücrelerinin üretimi ve dağılımı hakkında ek değerlendirme gerekebilir; WBC tek başına neden göstermez.",
    relatedCodes: ["NEUT_ABS", "NEUT_PCT", "LYMPH_ABS", "LYMPH_PCT", "MONO_ABS", "MONO_PCT", "EOS_ABS", "EOS_PCT", "BASO_ABS", "BASO_PCT"],
  },
  RBC: {
    subject: "Eritrositler",
    whatItIs: "Eritrositler, kanda en fazla bulunan kırmızı kan hücreleridir ve içlerinde hemoglobin taşırlar.",
    bodyRole: "Hemoglobin aracılığıyla akciğerlerden dokulara oksijen taşınmasına ve karbondioksitin geri taşınmasına katkı sağlarlar.",
    lowMeaning: "Düşük RBC; anemiyle ilişkili tablolar, kan kaybı, bazı besin öğesi eksiklikleri veya kemik iliği üretiminin azalması gibi birçok nedenle görülebilir.",
    highMeaning: "Yüksek RBC; sıvı kaybına bağlı yoğunlaşma, yüksek rakım, kronik düşük oksijen durumları veya eritrosit üretiminin arttığı bazı tablolarla ilişkili olabilir.",
    whyOutOfRangeMatters: "Eritrosit sayısı oksijen taşıma kapasitesinin yalnızca bir parçasıdır; hemoglobin, hematokrit ve eritrosit indeksleriyle birlikte anlam kazanır.",
    relatedCodes: ["HGB", "HCT", "MCV", "MCH", "MCHC", "RDW_CV", "RDW_SD"],
  },
  HGB: {
    subject: "Hemoglobin",
    whatItIs: "Hemoglobin, eritrositlerin içinde bulunan ve demir içeren oksijen taşıyıcı proteindir.",
    bodyRole: "Akciğerlerde oksijeni bağlar, dokulara taşır ve karbondioksit taşınmasına da katkı sağlar.",
    lowMeaning: "Düşük hemoglobin anemiyle uyumlu olabilir; demir, B12 veya folat yetersizliği, kan kaybı ve başka birçok neden değerlendirmede rol oynayabilir.",
    highMeaning: "Yüksek hemoglobin; sıvı kaybı, yüksek rakım, sigara/düşük oksijen maruziyeti veya eritrosit üretiminin arttığı bazı durumlarla ilişkili olabilir.",
    whyOutOfRangeMatters: "Hemoglobin belirgin düşük olduğunda dokulara taşınabilen oksijen miktarı azalabilir; belirgin yüksek olduğunda ise kanın hücresel yoğunluğu artabilir. Klinik önem düzeye ve nedene göre değişir.",
    relatedCodes: ["RBC", "HCT", "MCV", "MCH", "MCHC", "RDW_CV", "FERRITIN", "IRON", "TIBC"],
  },
  HCT: {
    subject: "Hematokrit",
    whatItIs: "Hematokrit bir hücre veya protein değil, kan hacminin yaklaşık ne kadarının eritrositlerden oluştuğunu gösteren orandır.",
    bodyRole: "Doğrudan biyolojik görevi olan bir madde değildir; eritrosit yoğunluğu ve kanın hücresel bileşimi hakkında bilgi veren ölçümdür.",
    lowMeaning: "Düşük hematokrit; anemi, kan kaybı veya kanın sıvı kısmının arttığı durumlarla ilişkili olabilir.",
    highMeaning: "Yüksek hematokrit; sıvı kaybı, yüksek rakım, kronik düşük oksijen veya eritrosit sayısının arttığı durumlarla ilişkili olabilir.",
    whyOutOfRangeMatters: "Hematokritteki belirgin değişiklikler oksijen taşıyan hücrelerin dolaşımdaki oranını yansıtır; RBC ve hemoglobinle birlikte değerlendirilir.",
    relatedCodes: ["RBC", "HGB", "MCV", "MCH", "MCHC"],
  },
  MCV: {
    subject: "MCV",
    whatItIs: "MCV, tek tek eritrositlerin ortalama hacmini yani ortalama büyüklüğünü gösteren eritrosit indeksidir.",
    bodyRole: "MCV'nin kendisinin vücutta bir görevi yoktur; eritrositlerin boyut özelliklerini sınıflandırmaya yardımcı olan hesaplanmış ölçümdür.",
    lowMeaning: "Düşük MCV, daha küçük eritrositlerle seyreden mikrositik bir görünümü düşündürebilir; demir eksikliği ve bazı kalıtsal hemoglobin bozuklukları olası nedenler arasındadır.",
    highMeaning: "Yüksek MCV, daha büyük eritrositlerle seyreden makrositik bir görünümü düşündürebilir; B12/folat yetersizliği, alkol kullanımı, bazı ilaçlar ve başka nedenlerle ilişkili olabilir.",
    whyOutOfRangeMatters: "MCV, anemi veya eritrosit yapısındaki değişikliklerin yönünü sınıflandırmaya yardımcı olur ancak nedeni tek başına belirlemez.",
    relatedCodes: ["HGB", "RBC", "HCT", "MCH", "MCHC", "RDW_CV", "RDW_SD", "FERRITIN", "VITAMIN_B12", "FOLATE"],
  },
  MCH: {
    subject: "MCH",
    whatItIs: "MCH, bir eritrositte ortalama ne kadar hemoglobin bulunduğunu gösteren hesaplanmış eritrosit indeksidir.",
    bodyRole: "MCH'nin kendisinin biyolojik görevi yoktur; eritrositlerin hemoglobin içeriğini sayısal olarak tanımlar.",
    lowMeaning: "Düşük MCH, eritrosit başına hemoglobin miktarının azaldığını gösterir ve sıklıkla küçük/soluk eritrositlerle seyreden tablolarla birlikte görülebilir.",
    highMeaning: "Yüksek MCH çoğu zaman eritrositlerin daha büyük olduğu durumlarla birlikte görülür; tek başına özgül bir neden göstermez.",
    whyOutOfRangeMatters: "MCH, hemoglobin dağılımını anlamaya yardımcı olur ve özellikle MCV, MCHC, HGB ve RDW ile birlikte yorumlanır.",
    relatedCodes: ["HGB", "MCV", "MCHC", "RBC", "RDW_CV", "RDW_SD"],
  },
  MCHC: {
    subject: "MCHC",
    whatItIs: "MCHC, eritrositlerin içindeki ortalama hemoglobin yoğunluğunu gösteren hesaplanmış indekstir.",
    bodyRole: "Doğrudan fizyolojik görevi olan bir madde değildir; eritrositlerin hemoglobin yoğunluğunu tanımlayan laboratuvar göstergesidir.",
    lowMeaning: "Düşük MCHC, eritrositlerin hemoglobin yoğunluğunun azaldığını gösterebilir ve demir eksikliği gibi hipokromik tablolarla ilişkili olabilir.",
    highMeaning: "Yüksek MCHC daha seyrektir; bazı eritrosit şekil bozuklukları, hemoliz veya ölçümle ilgili etkenlerle ilişkili olabilir ve doğrulama gerekebilir.",
    whyOutOfRangeMatters: "MCHC, eritrositlerin hemoglobin içeriğinin yoğunluğunu değerlendirmeye yardımcı olur; tek başına tanı amacıyla kullanılmaz.",
    relatedCodes: ["HGB", "MCV", "MCH", "RBC", "RDW_CV"],
  },
  RDW_CV: {
    subject: "RDW-CV",
    whatItIs: "RDW-CV, eritrositlerin boyutlarının birbirinden ne kadar farklı olduğunu yüzde olarak gösteren dağılım indeksidir.",
    bodyRole: "RDW-CV'nin kendisinin vücutta görevi yoktur; eritrosit boyut değişkenliğini ölçer.",
    lowMeaning: "Düşük RDW-CV genellikle eritrosit boyutlarının birbirine benzer olduğunu gösterir ve çoğu durumda tek başına özel bir sorun anlamına gelmez.",
    highMeaning: "Yüksek RDW-CV, eritrosit boyutlarının daha değişken olduğunu gösterir; demir, B12 veya folat yetersizliği gibi farklı eritrosit üretim tablolarında görülebilir.",
    whyOutOfRangeMatters: "Yüksek RDW, eritrosit popülasyonunun homojen olmadığını gösteren bir ipucudur; MCV ve hemoglobinle birlikte neden ayrımına katkı sağlar.",
    relatedCodes: ["MCV", "RDW_SD", "HGB", "RBC", "FERRITIN", "VITAMIN_B12", "FOLATE"],
  },
  RDW_SD: {
    subject: "RDW-SD",
    whatItIs: "RDW-SD, eritrosit boyut dağılımının genişliğini fL cinsinden ölçen eritrosit indeksidir.",
    bodyRole: "RDW-SD'nin biyolojik görevi yoktur; farklı büyüklükte eritrositlerin dağılımını sayısallaştırır.",
    lowMeaning: "Düşük RDW-SD çoğunlukla eritrosit boyutlarının birbirine yakın olduğunu gösterir ve tek başına genellikle özel bir klinik anlam taşımaz.",
    highMeaning: "Yüksek RDW-SD, eritrosit boyutlarındaki değişkenliğin arttığını gösterir; çeşitli anemi tiplerinde ve eritrosit üretiminin değiştiği durumlarda görülebilir.",
    whyOutOfRangeMatters: "RDW-SD özellikle MCV, RDW-CV ve hemoglobinle birlikte eritrositlerin boyut örüntüsünü anlamaya yardımcı olur.",
    relatedCodes: ["RDW_CV", "MCV", "HGB", "RBC", "MCH", "MCHC"],
  },
  PLT: {
    subject: "Trombositler",
    whatItIs: "Trombositler, kemik iliğinde üretilen ve dolaşımda bulunan küçük hücresel parçalardır.",
    bodyRole: "Damar hasarı olduğunda birbirine ve hasarlı yüzeye tutunarak kanamanın durdurulmasına, pıhtı tıkacının oluşmasına ve onarım sinyallerine katkı sağlarlar.",
    lowMeaning: "Düşük trombosit sayısı üretimin azalması, tüketimin/yıkımın artması, bazı enfeksiyonlar veya ilaçlar gibi birçok nedenle görülebilir. Düzey belirgin düştükçe kanama eğilimi önem kazanabilir.",
    highMeaning: "Yüksek trombosit sayısı inflamasyon, demir eksikliği, enfeksiyon sonrası yanıt veya kemik iliği kaynaklı bazı durumlarla ilişkili olabilir.",
    whyOutOfRangeMatters: "Trombosit sayısındaki belirgin değişiklikler kanama ve pıhtılaşma dengesi açısından önemli olabilir; düzeyin derecesi ve nedeni belirleyicidir.",
    relatedCodes: ["MPV", "PDW", "PCT", "P_LCR", "HGB", "WBC"],
  },
  MPV: {
    subject: "MPV",
    whatItIs: "MPV, dolaşımdaki trombositlerin ortalama hacmini yani ortalama büyüklüğünü gösteren indekstir.",
    bodyRole: "MPV'nin kendisinin biyolojik görevi yoktur; trombositlerin boyut dağılımı ve üretim örüntüsü hakkında tamamlayıcı bilgi verir.",
    lowMeaning: "Düşük MPV daha küçük ortalama trombosit hacmini gösterir; yorum PLT sayısı ve klinik bağlama göre değişir.",
    highMeaning: "Yüksek MPV daha büyük ortalama trombosit hacmini gösterir; genç trombositlerin dolaşıma çıkması veya farklı trombosit üretim/tüketim örüntüleriyle ilişkili olabilir.",
    whyOutOfRangeMatters: "MPV tek başına pıhtılaşma bozukluğu göstermez; PLT, PDW ve PCT ile birlikte değerlendirilmesi daha anlamlıdır.",
    relatedCodes: ["PLT", "PDW", "PCT", "P_LCR"],
  },
  PDW: {
    subject: "PDW",
    whatItIs: "PDW, trombositlerin büyüklüklerinin birbirinden ne kadar farklı olduğunu gösteren trombosit dağılım indeksidir.",
    bodyRole: "PDW'nin kendisinin vücutta görevi yoktur; trombosit boyut değişkenliğini ölçer.",
    lowMeaning: "Düşük PDW, trombosit boyutlarının daha benzer olduğunu gösterebilir ve çoğu zaman tek başına özgül bir hastalık göstergesi değildir.",
    highMeaning: "Yüksek PDW, trombosit boyutlarının daha değişken olduğunu gösterir; trombosit üretimi veya aktivasyonunun değiştiği çeşitli durumlarda görülebilir.",
    whyOutOfRangeMatters: "PDW, PLT ve MPV ile birlikte trombosit popülasyonunun yapısı hakkında tamamlayıcı bilgi sağlar.",
    relatedCodes: ["PLT", "MPV", "PCT", "P_LCR"],
  },
  P_LCR: {
    subject: "P-LCR",
    whatItIs: "P-LCR, büyük hacimli trombositlerin toplam trombositler içindeki yüzdesini gösteren indekstir.",
    bodyRole: "P-LCR'nin doğrudan biyolojik görevi yoktur; trombosit boyut dağılımının büyük trombositler yönünü sayısallaştırır.",
    lowMeaning: "Düşük P-LCR, büyük trombositlerin oranının daha düşük olduğunu gösterir; tek başına özgül bir neden belirtmez.",
    highMeaning: "Yüksek P-LCR, büyük trombosit oranının arttığını gösterir ve trombosit üretim/tüketim örüntüsündeki değişikliklerle ilişkili olabilir.",
    whyOutOfRangeMatters: "P-LCR tek başına pıhtılaşma işlevini göstermez; PLT, MPV ve PDW ile birlikte değerlendirilir.",
    relatedCodes: ["PLT", "MPV", "PDW", "PCT"],
  },
  PCT: {
    subject: "Plateletkrit",
    whatItIs: "Bu raporda yüzde birimiyle verilen PCT, prokalsitonin değil plateletkrittir. Toplam kan hacmi içinde trombositlerin kapladığı yaklaşık hacim payını gösteren indekstir.",
    bodyRole: "Plateletkritin kendisinin biyolojik görevi yoktur; trombosit sayısı ile ortalama trombosit hacminin birlikte oluşturduğu toplam trombosit kütlesi hakkında bilgi verir.",
    lowMeaning: "Düşük plateletkrit, toplam dolaşımdaki trombosit hacminin düşük olduğunu gösterir; düşük PLT veya düşük MPV ile birlikte görülebilir.",
    highMeaning: "Yüksek plateletkrit, toplam trombosit hacminin arttığını gösterir; yüksek PLT ve/veya MPV ile ilişkili olabilir.",
    whyOutOfRangeMatters: "Plateletkrit, trombosit sistemini tamamlayan bir indekstir; kanama veya pıhtılaşma riski hakkında tek başına karar verdirmez.",
    relatedCodes: ["PLT", "MPV", "PDW", "P_LCR"],
  },
  NEUT_ABS: {
    subject: "Nötrofiller",
    whatItIs: "Nötrofiller, doğuştan bağışıklık sisteminin en önemli beyaz kan hücresi gruplarından biridir.",
    bodyRole: "Özellikle bakteriler ve bazı mantarlar gibi mikroorganizmaları hızla tanıyıp fagosite ederek erken savunmada görev alırlar.",
    lowMeaning: "Düşük mutlak nötrofil sayısı; bazı viral enfeksiyonlar, ilaçlar, kemik iliği baskılanması veya başka nedenlerle görülebilir. Düşüklük belirgin olduğunda enfeksiyonlara karşı savunma azalabilir.",
    highMeaning: "Yüksek nötrofil sayısı; bakteriyel enfeksiyon, inflamasyon, stres yanıtı, sigara veya kortikosteroid kullanımı gibi birçok durumla ilişkili olabilir.",
    whyOutOfRangeMatters: "Mutlak nötrofil sayısı, nötrofil yüzdesinden daha doğrudan hücre miktarını gösterir ve belirgin düşüklükte enfeksiyon riski açısından önem kazanır.",
    relatedCodes: ["NEUT_PCT", "WBC", "LYMPH_ABS", "NLR"],
  },
  NEUT_PCT: {
    subject: "Nötrofiller",
    whatItIs: "Nötrofiller doğuştan bağışıklığın erken yanıt veren beyaz kan hücreleridir; NEUT% bunların toplam lökositler içindeki oranını gösterir.",
    bodyRole: "Mikroorganizmaları fagosite etme ve akut inflamatuvar yanıta katılma görevleri vardır.",
    lowMeaning: "Düşük NEUT% bazen diğer lökosit gruplarının oranının artmasına bağlı göreli bir değişiklik olabilir; mutlak nötrofil sayısı daha belirleyicidir.",
    highMeaning: "Yüksek NEUT% enfeksiyon, inflamasyon veya stres yanıtında görülebilir; ancak mutlak sayı ve toplam WBC birlikte değerlendirilmelidir.",
    whyOutOfRangeMatters: "Yüzde değerleri hücrelerin birbirine göre dağılımını gösterdiği için tek başına hücre sayısını ifade etmez.",
    relatedCodes: ["NEUT_ABS", "WBC", "LYMPH_PCT", "NLR"],
  },
  LYMPH_ABS: {
    subject: "Lenfositler",
    whatItIs: "Lenfositler; B hücreleri, T hücreleri ve NK hücrelerini kapsayan beyaz kan hücresi grubudur.",
    bodyRole: "Antikor üretimi, bağışıklık hafızası, enfekte hücrelerin tanınması ve hücresel bağışıklık gibi özgül savunma görevlerine katılırlar.",
    lowMeaning: "Düşük lenfosit sayısı; akut stres, bazı enfeksiyonlar, kortikosteroidler, bağışıklık baskılanması ve başka nedenlerle görülebilir.",
    highMeaning: "Yüksek lenfosit sayısı özellikle bazı viral enfeksiyonlarda ve daha seyrek olarak hematolojik durumlarda görülebilir.",
    whyOutOfRangeMatters: "Mutlak lenfosit sayısı bağışıklık hücrelerinin gerçek miktarını gösterir; kalıcı veya belirgin değişiklikler diğer lökositlerle birlikte değerlendirilir.",
    relatedCodes: ["LYMPH_PCT", "WBC", "NEUT_ABS", "NLR"],
  },
  LYMPH_PCT: {
    subject: "Lenfositler",
    whatItIs: "Lenfositler özgül bağışıklıkta görev alan beyaz kan hücreleridir; LYMPH% toplam lökositler içindeki paylarını gösterir.",
    bodyRole: "Bağışıklık hafızası, antikor yanıtı ve hücresel bağışıklıkta önemli görevleri vardır.",
    lowMeaning: "Düşük lenfosit yüzdesi bazen nötrofil gibi başka lökosit gruplarının göreli artışından kaynaklanabilir; mutlak lenfosit sayısı önemlidir.",
    highMeaning: "Yüksek lenfosit yüzdesi viral enfeksiyonlarda veya diğer lökosit gruplarının azalmasına bağlı göreli değişikliklerde görülebilir.",
    whyOutOfRangeMatters: "Yüzde değerinin anlamı toplam WBC ve mutlak lenfosit sayısı bilinmeden sınırlıdır.",
    relatedCodes: ["LYMPH_ABS", "WBC", "NEUT_PCT", "NLR"],
  },
  MONO_ABS: {
    subject: "Monositler",
    whatItIs: "Monositler, dolaşımdaki beyaz kan hücrelerinden biridir ve dokulara geçtiklerinde makrofaj benzeri hücrelere farklılaşabilirler.",
    bodyRole: "Mikroorganizmaların ve hücresel artıkların temizlenmesine, antijen sunumuna ve inflamatuvar yanıtın düzenlenmesine katkı sağlarlar.",
    lowMeaning: "Düşük monosit sayısı çoğu zaman tek başına özgül değildir; kemik iliği baskılanması veya diğer lökosit değişiklikleriyle birlikte görülebilir.",
    highMeaning: "Yüksek monosit sayısı bazı kronik enfeksiyonlar, inflamatuvar durumlar veya enfeksiyon sonrası iyileşme dönemleriyle ilişkili olabilir.",
    whyOutOfRangeMatters: "Monosit değişiklikleri genellikle WBC ve diğer lökosit alt gruplarıyla birlikte anlam kazanır.",
    relatedCodes: ["MONO_PCT", "WBC", "NEUT_ABS", "LYMPH_ABS"],
  },
  MONO_PCT: {
    subject: "Monositler",
    whatItIs: "Monositler temizleme ve inflamatuvar yanıt süreçlerine katılan beyaz kan hücreleridir; MONO% toplam lökositler içindeki oranlarını gösterir.",
    bodyRole: "Hücresel artıkların temizlenmesi, mikroorganizmaların fagositozu ve bağışıklık yanıtının düzenlenmesine katkı sağlarlar.",
    lowMeaning: "Düşük monosit yüzdesi çoğu zaman tek başına özgül değildir ve diğer lökosit oranlarının değişiminden etkilenebilir.",
    highMeaning: "Yüksek monosit yüzdesi bazı enfeksiyon, inflamasyon veya iyileşme süreçlerinde görülebilir; mutlak monosit sayısı daha doğrudan bilgi verir.",
    whyOutOfRangeMatters: "Oransal değişiklikler toplam WBC ve mutlak monosit sayısıyla birlikte değerlendirilmelidir.",
    relatedCodes: ["MONO_ABS", "WBC", "NEUT_PCT", "LYMPH_PCT"],
  },
  EOS_ABS: {
    subject: "Eozinofiller",
    whatItIs: "Eozinofiller, beyaz kan hücrelerinin bir alt grubudur ve kanda normalde görece az sayıda bulunurlar.",
    bodyRole: "Özellikle bazı parazitlere karşı savunmada; alerjik yanıtların ve bazı inflamatuvar süreçlerin düzenlenmesinde görev alırlar.",
    lowMeaning: "Düşük eozinofil sayısı çoğu zaman tek başına önemli bir hastalık göstergesi değildir; akut stres veya kortikosteroid etkisiyle azalabilir.",
    highMeaning: "Yüksek eozinofil sayısı; alerjik hastalıklar, bazı paraziter enfeksiyonlar, ilaç reaksiyonları ve bazı inflamatuvar/hematolojik durumlarla ilişkili olabilir.",
    whyOutOfRangeMatters: "Belirgin veya kalıcı eozinofil yüksekliği, nedenin alerjik, enfeksiyöz veya başka bir süreç olup olmadığını ayırt etmek için klinik bağlam gerektirebilir.",
    relatedCodes: ["EOS_PCT", "WBC", "BASO_ABS", "BASO_PCT"],
  },
  EOS_PCT: {
    subject: "Eozinofiller",
    whatItIs: "Eozinofiller, bağışıklık sisteminde görev yapan beyaz kan hücrelerinden biridir. EO% ise toplam beyaz kan hücrelerinin yüzde kaçının eozinofil olduğunu gösterir.",
    bodyRole: "Eozinofiller özellikle bazı parazitlere karşı savunmada, alerjik reaksiyonlarda ve belirli inflamatuvar süreçlerde rol oynarlar.",
    lowMeaning: "Düşük eozinofil oranı çoğu zaman tek başına özel bir sorun göstermez; akut stres veya kortikosteroid etkisiyle görülebilir.",
    highMeaning: "Yüksek eozinofil oranı alerjik durumlar, bazı paraziter enfeksiyonlar, ilaç reaksiyonları ve başka inflamatuvar süreçlerle ilişkili olabilir.",
    whyOutOfRangeMatters: "EO% bir oran olduğu için mutlak eozinofil sayısı ve toplam WBC ile birlikte değerlendirilmesi, gerçek hücre artışını ayırt etmeye yardımcı olur.",
    relatedCodes: ["EOS_ABS", "WBC", "BASO_PCT", "BASO_ABS"],
  },
  BASO_ABS: {
    subject: "Bazofiller",
    whatItIs: "Bazofiller, dolaşımda az sayıda bulunan beyaz kan hücrelerinden biridir.",
    bodyRole: "Histamin ve başka mediyatörleri salarak alerjik ve inflamatuvar yanıtlara katkı sağlarlar.",
    lowMeaning: "Düşük bazofil sayısı çoğu zaman tek başına klinik açıdan belirleyici değildir ve normal kişilerde sıfıra çok yakın olabilir.",
    highMeaning: "Yüksek bazofil sayısı alerjik/inflamatuvar durumlar, bazı hormonal değişiklikler ve daha seyrek bazı hematolojik tablolarla ilişkili olabilir.",
    whyOutOfRangeMatters: "Bazofil yüksekliği kalıcıysa toplam WBC ve diğer lökosit alt gruplarıyla birlikte değerlendirilir.",
    relatedCodes: ["BASO_PCT", "WBC", "EOS_ABS", "EOS_PCT"],
  },
  BASO_PCT: {
    subject: "Bazofiller",
    whatItIs: "Bazofiller alerjik ve inflamatuvar yanıtlara katılan beyaz kan hücreleridir; BASO% toplam lökositler içindeki oranlarını gösterir.",
    bodyRole: "Histamin gibi mediyatörlerin salınmasına katkı sağlayarak bağışıklık yanıtında rol oynarlar.",
    lowMeaning: "Düşük bazofil yüzdesi çoğu zaman tek başına klinik açıdan önemli değildir ve bazofiller normalde zaten küçük bir lökosit grubudur.",
    highMeaning: "Yüksek bazofil yüzdesi alerjik/inflamatuvar süreçler veya başka lökosit dağılım değişiklikleriyle ilişkili olabilir.",
    whyOutOfRangeMatters: "BASO% oransal bir ölçümdür; mutlak bazofil sayısı ve toplam WBC ile birlikte değerlendirilmelidir.",
    relatedCodes: ["BASO_ABS", "WBC", "EOS_PCT", "EOS_ABS"],
  },
  NLR: {
    subject: "Nötrofil / Lenfosit Oranı",
    whatItIs: "NLR, mutlak nötrofil sayısının mutlak lenfosit sayısına bölünmesiyle elde edilen türetilmiş bir orandır; doğrudan ölçülen bir hücre veya madde değildir.",
    bodyRole: "NLR'nin vücutta bir görevi yoktur. Bağışıklık hücrelerinin göreli dağılımını tek sayıda özetlemek için kullanılan hesaplanmış göstergedir.",
    lowMeaning: "Düşük NLR, nötrofil/lenfosit dengesinin lenfositler yönüne kaydığını gösterebilir; laboratuvarlar için evrensel tek bir referans aralığı yoktur.",
    highMeaning: "Yüksek NLR, nötrofil artışı ve/veya lenfosit azalmasıyla görülebilir ve inflamasyon/stres gibi çeşitli durumlarla ilişkili olabilir.",
    whyOutOfRangeMatters: "NLR özgül bir tanı testi değildir ve bağlamdan bağımsız sabit bir eşik kullanmak yanıltıcı olabilir; NEUT ve LYMPH mutlak değerleri esas alınmalıdır.",
    relatedCodes: ["NEUT_ABS", "LYMPH_ABS", "WBC", "NEUT_PCT", "LYMPH_PCT"],
  },
  HBA1C: {
    subject: "HbA1c",
    whatItIs: "HbA1c, glukozun hemoglobine bağlanmasıyla oluşan glikozillenmiş hemoglobin oranını ölçen laboratuvar göstergesidir.",
    bodyRole: "HbA1c'nin ayrı bir fizyolojik görevi yoktur; eritrositlerin yaşam süresi boyunca glukoz maruziyetini yansıtarak yaklaşık son birkaç aylık kan şekeri örüntüsü hakkında bilgi verir.",
    lowMeaning: "Düşük HbA1c, düşük ortalama glukozla ilişkili olabileceği gibi eritrosit ömrünü kısaltan bazı durumlarda da beklenenden düşük ölçülebilir.",
    highMeaning: "Yüksek HbA1c, son aylardaki ortalama kan şekeri düzeylerinin daha yüksek seyrettiğini gösterebilir ve diyabet/prediyabet değerlendirmesinde kullanılan göstergelerden biridir.",
    whyOutOfRangeMatters: "HbA1c uzun dönem glukoz maruziyetini yansıtır; tanısal yorum kullanılan yönteme, klinik duruma ve gerektiğinde glukoz ölçümlerine göre yapılır.",
    relatedCodes: ["GLUCOSE", "HGB", "RBC", "MCV"],
  },
  TIBC: {
    subject: "Total Demir Bağlama Kapasitesi",
    whatItIs: "TDBK/TIBC, başta transferrin olmak üzere kandaki demir taşıyan proteinlerin ne kadar demir bağlayabildiğini dolaylı olarak gösteren laboratuvar ölçümüdür.",
    bodyRole: "TIBC'nin kendisinin biyolojik görevi yoktur; transferrinin demir taşıma kapasitesi hakkında bilgi verir. Transferrin demiri kanda taşır.",
    lowMeaning: "Düşük TIBC; inflamasyon, bazı kronik hastalıklar, karaciğerle ilişkili durumlar veya demir taşıma proteininin azaldığı tablolarla ilişkili olabilir.",
    highMeaning: "Yüksek TIBC sıklıkla demir eksikliğiyle ilişkili olabilir; ancak serum demiri ve ferritin olmadan demir depoları hakkında tek başına karar verilemez.",
    whyOutOfRangeMatters: "Demir metabolizmasını anlamak için TIBC genellikle ferritin, serum demiri ve transferrin satürasyonuyla birlikte değerlendirilir.",
    relatedCodes: ["IRON", "FERRITIN", "HGB", "MCV", "MCH", "RDW_CV"],
  },
  IRON: {
    subject: "Serum demiri",
    whatItIs: "Serum demiri, kanın serum kısmında transferrine bağlı olarak dolaşan demir miktarını ölçer.",
    bodyRole: "Demir hemoglobinin yapısında, oksijen taşınmasında ve birçok enzimin çalışmasında temel rol oynar.",
    lowMeaning: "Düşük serum demiri demir eksikliğiyle ilişkili olabilir; inflamasyon ve gün içi değişimler de sonucu etkileyebilir.",
    highMeaning: "Yüksek serum demiri aşırı demir yükü, bazı karaciğer/hemoliz durumları veya yakın zamanda alınan demir gibi etkenlerle ilişkili olabilir.",
    whyOutOfRangeMatters: "Serum demiri tek başına demir depolarını göstermez; ferritin, TIBC ve transferrin satürasyonu ile birlikte değerlendirilir.",
    relatedCodes: ["FERRITIN", "TIBC", "HGB", "MCV", "MCH", "RDW_CV"],
  },
  FERRITIN: {
    subject: "Ferritin",
    whatItIs: "Ferritin, hücrelerde demiri depolayan proteindir; kandaki ferritin düzeyi vücudun demir depoları hakkında dolaylı bilgi verir.",
    bodyRole: "Demiri güvenli biçimde depolayıp gerektiğinde kullanılabilir halde tutmaya katkı sağlar.",
    lowMeaning: "Düşük ferritin çoğu zaman azalmış demir depolarını destekleyen güçlü bir bulgudur ve demir eksikliği değerlendirmesinde önemlidir.",
    highMeaning: "Yüksek ferritin demir yüküyle ilişkili olabileceği gibi inflamasyon, enfeksiyon, karaciğer hastalıkları ve başka durumlarda da yükselebilir.",
    whyOutOfRangeMatters: "Ferritin hem demir deposu göstergesi hem de inflamasyondan etkilenebilen bir proteindir; bağlam ve diğer demir testleri önemlidir.",
    relatedCodes: ["IRON", "TIBC", "HGB", "MCV", "MCH", "RDW_CV"],
  },
  GLUCOSE: {
    subject: "Glukoz",
    whatItIs: "Glukoz, kanda dolaşan temel şeker ve birçok hücrenin başlıca enerji kaynaklarından biridir.",
    bodyRole: "Özellikle beyin ve çalışan kaslar için önemli enerji sağlar; düzeyi insülin ve başka hormonlarla düzenlenir.",
    lowMeaning: "Düşük glukoz terleme, titreme, çarpıntı, dikkat bozukluğu gibi hipoglisemi belirtileriyle ilişkili olabilir; ölçüm koşulu ve ilaçlar önemlidir.",
    highMeaning: "Yüksek glukoz yemek sonrası geçici artıştan diyabetle ilişkili kalıcı yüksekliğe kadar farklı nedenlerle görülebilir.",
    whyOutOfRangeMatters: "Belirgin veya tekrarlayan glukoz değişiklikleri enerji metabolizmasını etkileyebilir; açlık/tokluk durumu ve HbA1c ile birlikte değerlendirilir.",
    relatedCodes: ["HBA1C", "INSULIN"],
  },
  INSULIN: {
    subject: "İnsülin",
    whatItIs: "İnsülin, pankreasın beta hücrelerinden salgılanan hormondur.",
    bodyRole: "Glukozun hücrelere alınmasına, karaciğer ve kaslarda enerji depolanmasına ve yağ/protein metabolizmasının düzenlenmesine katkı sağlar.",
    lowMeaning: "Düşük insülin açlıkta fizyolojik olabilir; glukoz yüksekken yetersiz insülin üretimi farklı bir anlam taşır ve bağlam gerekir.",
    highMeaning: "Yüksek insülin, özellikle glukozla birlikte değerlendirildiğinde insülin direnciyle ilişkili olabilir; yemek sonrası fizyolojik olarak da yükselir.",
    whyOutOfRangeMatters: "İnsülinin anlamı örnekleme zamanı ve glukoz düzeyine güçlü biçimde bağlıdır; tek başına yorumlanmamalıdır.",
    relatedCodes: ["GLUCOSE", "HBA1C"],
  },
  VITAMIN_D: {
    subject: "25-OH D vitamini",
    whatItIs: "25-hidroksi D vitamini, vücudun D vitamini durumunu değerlendirmede en sık kullanılan dolaşımdaki formdur.",
    bodyRole: "Kalsiyum-fosfor dengesine, kemik mineralizasyonuna ve çeşitli hücresel süreçlere katkı sağlar.",
    lowMeaning: "Düşük 25-OH D düzeyi yetersiz güneş maruziyeti, düşük alım, emilim sorunları veya başka nedenlerle ilişkili olabilir.",
    highMeaning: "Belirgin yüksek D vitamini düzeyleri çoğunlukla aşırı dış kaynak alımıyla ilişkilidir ve kalsiyum yüksekliği gibi sorunlara eşlik edebilir.",
    whyOutOfRangeMatters: "D vitamini değerlendirmesinde laboratuvar yöntemi, eşlik eden kalsiyum ve kişisel klinik durum önemlidir; ürün/doz önerisi uzman değerlendirmesi gerektirir.",
    relatedCodes: [],
  },
  VITAMIN_B12: {
    subject: "Vitamin B12",
    whatItIs: "B12, besinlerden alınan ve vücutta depolanabilen suda çözünen bir vitamindir.",
    bodyRole: "DNA sentezi, normal kan hücresi üretimi ve sinir sisteminin işlevleri için gereklidir.",
    lowMeaning: "Düşük B12; yetersiz alım, emilim bozukluğu veya bazı ilaçlarla ilişkili olabilir ve anemi/nörolojik bulgulara katkı sağlayabilir.",
    highMeaning: "Yüksek B12 dış kaynak kullanımına bağlı olabileceği gibi bazı karaciğer, böbrek veya hematolojik durumlarda da görülebilir.",
    whyOutOfRangeMatters: "Sınırda değerlerde klinik bulgular ve gerektiğinde tamamlayıcı testler yorumun doğruluğunu artırabilir.",
    relatedCodes: ["HGB", "MCV", "RDW_CV", "FOLATE"],
  },
  FOLATE: {
    subject: "Folat",
    whatItIs: "Folat, B9 vitamini ailesindeki bileşiklerin genel adıdır ve hücrelerin hızlı bölündüğü dokularda önemlidir.",
    bodyRole: "DNA sentezi, hücre bölünmesi ve normal kırmızı kan hücresi üretiminde görev alır.",
    lowMeaning: "Düşük folat yetersiz alım, emilim sorunları, artmış gereksinim veya bazı ilaçlarla ilişkili olabilir ve makrositik anemiye katkı sağlayabilir.",
    highMeaning: "Yüksek folat çoğunlukla yüksek alımla ilişkilidir; tek başına genellikle toksisite göstergesi değildir ancak B12 durumu ile birlikte değerlendirme gerekebilir.",
    whyOutOfRangeMatters: "Folat, B12 ve eritrosit indeksleri birlikte değerlendirildiğinde kan hücresi üretimi hakkında daha anlamlı bilgi sağlar.",
    relatedCodes: ["VITAMIN_B12", "HGB", "MCV", "RDW_CV"],
  },
  CREATININE: {
    subject: "Kreatinin",
    whatItIs: "Kreatinin, kaslardaki kreatin metabolizması sırasında oluşan atık üründür.",
    bodyRole: "Belirgin bir yararlı fizyolojik görevi yoktur; böbrekler tarafından süzüldüğü için kandaki düzeyi böbrek filtrasyonu hakkında dolaylı bilgi verir.",
    lowMeaning: "Düşük kreatinin çoğunlukla düşük kas kütlesi, gebelik veya yüksek sıvı durumu gibi etkenlerle ilişkili olabilir.",
    highMeaning: "Yüksek kreatinin böbrek filtrasyonunun azalması, sıvı kaybı, yüksek kas kütlesi veya bazı ilaç/etkenlerle ilişkili olabilir.",
    whyOutOfRangeMatters: "Kreatinin tek başına böbrek fonksiyonunu tam tanımlamaz; eGFR ve klinik bağlamla birlikte yorumlanır.",
    relatedCodes: ["EGFR", "BUN"],
  },
  EGFR: {
    subject: "eGFR",
    whatItIs: "eGFR, kreatinin ve demografik bilgiler kullanılarak böbreklerin süzme hızını tahmin eden hesaplanmış göstergedir.",
    bodyRole: "eGFR'nin vücutta görevi yoktur; böbrek filtrasyon kapasitesini yaklaşık olarak ifade eder.",
    lowMeaning: "Düşük eGFR böbrek filtrasyonunun azalmış olabileceğini gösterir; tek bir ölçüm geçici değişikliklerden etkilenebilir ve süreklilik önemlidir.",
    highMeaning: "Yüksek eGFR çoğu zaman iyi filtrasyonla uyumlu olabilir; bazı durumlarda hiperfiltrasyon da söz konusu olabilir ve klinik bağlam gerekir.",
    whyOutOfRangeMatters: "eGFR'nin kalıcı düşüklüğü böbrek fonksiyonu açısından önemlidir; kreatinin ve önceki ölçümlerle trend değerlendirmesi yararlıdır.",
    relatedCodes: ["CREATININE", "BUN"],
  },
  BUN: {
    subject: "Üre azotu (BUN)",
    whatItIs: "BUN, proteinlerin parçalanması sonucu oluşan ürenin içerdiği azotun kandaki miktarını ölçer.",
    bodyRole: "Üre azotu bir metabolik atık göstergesidir ve büyük ölçüde böbrekler yoluyla uzaklaştırılır.",
    lowMeaning: "Düşük BUN düşük protein alımı, karaciğerle ilişkili durumlar veya yüksek sıvı durumu gibi etkenlerle görülebilir.",
    highMeaning: "Yüksek BUN sıvı kaybı, böbrek filtrasyonunda azalma, yüksek protein yıkımı veya gastrointestinal kanama gibi durumlarla ilişkili olabilir.",
    whyOutOfRangeMatters: "BUN sıvı ve protein durumundan güçlü biçimde etkilenir; kreatinin ve eGFR ile birlikte yorumlanır.",
    relatedCodes: ["CREATININE", "EGFR"],
  },
  TSH: {
    subject: "TSH",
    whatItIs: "TSH, hipofiz bezinden salgılanan ve tiroid bezini uyaran hormondur.",
    bodyRole: "Tiroid bezinin T4 ve T3 hormonlarını üretmesini ve salgılamasını düzenleyen ana geri bildirim sinyalidir.",
    lowMeaning: "Düşük TSH tiroid hormonlarının fazla olduğu durumlarda, bazı ilaçlarda veya hipofiz kaynaklı durumlarda görülebilir; fT4/fT3 ile birlikte yorumlanır.",
    highMeaning: "Yüksek TSH tiroid hormonlarının yetersiz olduğu primer hipotiroidi gibi durumlarla ilişkili olabilir; fT4 sonucu önemlidir.",
    whyOutOfRangeMatters: "TSH tiroid değerlendirmesinin temel testidir ancak neden ve klinik önem fT4/fT3 ve belirtilerle birlikte belirlenir.",
    relatedCodes: ["FT4", "FT3"],
  },
  FT3: {
    subject: "Serbest T3",
    whatItIs: "T3, tiroid hormonlarının biyolojik olarak aktif formlarından biridir; serbest T3 kanda proteine bağlı olmayan kısmı ölçer.",
    bodyRole: "Enerji kullanımı, ısı üretimi, kalp hızı ve birçok hücresel metabolik sürecin düzenlenmesine katkı sağlar.",
    lowMeaning: "Düşük fT3 tiroid hormon yetersizliğiyle ilişkili olabileceği gibi ağır hastalık veya düşük enerji alımı gibi tiroid dışı durumlarda da görülebilir.",
    highMeaning: "Yüksek fT3 hipertiroidiyle ilişkili olabilir ve çarpıntı, ısı intoleransı, kilo kaybı gibi belirtilerle birlikte değerlendirilebilir.",
    whyOutOfRangeMatters: "fT3 tek başına tiroid tanısı koydurmaz; TSH ve fT4 ile birlikte değerlendirilir.",
    relatedCodes: ["TSH", "FT4"],
  },
  FT4: {
    subject: "Serbest T4",
    whatItIs: "T4, tiroid bezinin ürettiği başlıca hormondur; serbest T4 kanda proteine bağlı olmayan biyolojik olarak kullanılabilir kısmı ölçer.",
    bodyRole: "Dokularda T3'e dönüşerek metabolizma, enerji kullanımı ve birçok organ sisteminin düzenlenmesine katkı sağlar.",
    lowMeaning: "Düşük fT4, özellikle TSH yüksekse primer hipotiroidiyle ilişkili olabilir; TSH düşük/normal olduğunda farklı nedenler düşünülür.",
    highMeaning: "Yüksek fT4, özellikle TSH düşükse hipertiroidiyle ilişkili olabilir; ilaçlar ve başka etkenler de sonucu etkileyebilir.",
    whyOutOfRangeMatters: "fT4, TSH ile birlikte tiroid hormon durumunu anlamada temel tamamlayıcı testtir.",
    relatedCodes: ["TSH", "FT3"],
  },
  TOTAL_CHOLESTEROL: {
    subject: "Total kolesterol",
    whatItIs: "Total kolesterol, farklı lipoprotein parçacıklarıyla taşınan kolesterolün toplam miktarını gösteren ölçümdür.",
    bodyRole: "Kolesterol hücre zarlarının, safra asitlerinin ve bazı hormonların yapımında kullanılır; kanda lipoproteinlerle taşınır.",
    lowMeaning: "Düşük total kolesterol çoğu zaman tek başına sorun değildir; beslenme, tiroid/karaciğer durumu veya kronik hastalıklar gibi etkenlerle ilişkili olabilir.",
    highMeaning: "Yüksek total kolesterol özellikle LDL yüksekliğiyle birlikte olduğunda kardiyovasküler risk değerlendirmesinde önem kazanır.",
    whyOutOfRangeMatters: "Total kolesterol tek başına yeterli değildir; LDL, HDL, trigliserid ve kişinin toplam kardiyovasküler risk profili birlikte değerlendirilir.",
    relatedCodes: ["LDL", "HDL", "TRIGLYCERIDES"],
  },
  LDL: {
    subject: "LDL kolesterol",
    whatItIs: "LDL, kolesterolü dolaşımda taşıyan lipoprotein parçacıklarından biridir; test LDL parçacıklarıyla taşınan kolesterol miktarını tahmin eder veya ölçer.",
    bodyRole: "LDL parçacıkları kolesterolü hücrelere ve dokulara taşır; kolesterol normal hücresel işlevler için gereklidir.",
    lowMeaning: "Düşük LDL çoğu kişide kardiyovasküler risk açısından olumsuz bir bulgu değildir; çok düşük değerlerin anlamı klinik bağlama göre değişir.",
    highMeaning: "Yüksek LDL, damar duvarında kolesterol birikimi ve aterosklerotik kardiyovasküler riskle ilişkili önemli bir göstergedir.",
    whyOutOfRangeMatters: "LDL hedefi herkeste aynı değildir; yaş, diyabet, tansiyon, sigara ve mevcut kardiyovasküler hastalık gibi riskler hedefi değiştirir.",
    relatedCodes: ["TOTAL_CHOLESTEROL", "HDL", "TRIGLYCERIDES"],
  },
  HDL: {
    subject: "HDL kolesterol",
    whatItIs: "HDL, kolesterolün dolaşımda taşınmasına katılan lipoprotein parçacıklarından biridir; test HDL ile taşınan kolesterol miktarını ölçer.",
    bodyRole: "Kolesterolün periferik dokulardan karaciğere geri taşınmasına katkı sağlar ve lipid metabolizmasının parçasıdır.",
    lowMeaning: "Düşük HDL kardiyovasküler risk profiliyle ilişkili olabilir; tek başına tedavi hedefi olarak değil toplam risk bağlamında değerlendirilir.",
    highMeaning: "Yüksek HDL çoğu zaman olumlu bir risk göstergesiyle ilişkilidir ancak çok yüksek değerler her zaman ek koruma anlamına gelmez.",
    whyOutOfRangeMatters: "HDL'nin anlamı LDL, trigliserid ve diğer kardiyovasküler risk etkenleriyle birlikte değerlendirilmelidir.",
    relatedCodes: ["TOTAL_CHOLESTEROL", "LDL", "TRIGLYCERIDES"],
  },
  TRIGLYCERIDES: {
    subject: "Trigliseridler",
    whatItIs: "Trigliseridler, yağ asitlerinin depolanıp taşındığı temel lipid biçimlerinden biridir.",
    bodyRole: "Vücudun enerji depolarından biridir; ihtiyaç olduğunda yağ dokusundan enerji üretiminde kullanılabilir.",
    lowMeaning: "Düşük trigliserid çoğu zaman klinik sorun değildir; düşük enerji alımı, malabsorpsiyon veya başka durumlarla ilişkili olabilir.",
    highMeaning: "Yüksek trigliserid; fazla enerji/alkol alımı, insülin direnci, diyabet, bazı ilaçlar ve genetik etkenlerle ilişkili olabilir. Çok yüksek düzeylerde pankreatit riski artabilir.",
    whyOutOfRangeMatters: "Trigliserid açlık/tokluk ve metabolik durumdan etkilenir; çok yüksek düzeyler ayrıca akut risk açısından önem taşır.",
    relatedCodes: ["TOTAL_CHOLESTEROL", "LDL", "HDL", "GLUCOSE", "HBA1C"],
  },
  ALT: {
    subject: "ALT",
    whatItIs: "ALT, aminoasit metabolizmasına katılan ve özellikle karaciğer hücrelerinde yoğun bulunan enzimdir.",
    bodyRole: "Hücre içinde aminoasitlerin işlenmesinde görev alır; kandaki ALT aktivitesi hücrelerden enzimin dolaşıma geçmesiyle artabilir.",
    lowMeaning: "Düşük ALT çoğu zaman klinik açıdan önemli değildir.",
    highMeaning: "Yüksek ALT karaciğer hücrelerinin etkilenmesiyle ilişkili olabilir; yağlı karaciğer, viral hepatit, ilaçlar ve başka nedenler olasıdır.",
    whyOutOfRangeMatters: "ALT yüksekliği karaciğer hasarının nedenini tek başına göstermez; AST, ALP, bilirubin ve klinik bağlamla birlikte değerlendirilir.",
    relatedCodes: ["AST", "ALP", "ALBUMIN"],
  },
  AST: {
    subject: "AST",
    whatItIs: "AST, aminoasit metabolizmasına katılan ve karaciğerin yanı sıra kas, kalp ve başka dokularda da bulunan enzimdir.",
    bodyRole: "Hücre içi aminoasit metabolizmasında görev alır; doku hasarında kana salınabilir.",
    lowMeaning: "Düşük AST çoğu zaman klinik açıdan önemli değildir.",
    highMeaning: "Yüksek AST karaciğer veya kas dokusunun etkilenmesi dahil farklı nedenlerle görülebilir; ALT ile birlikte örüntü önemlidir.",
    whyOutOfRangeMatters: "AST karaciğere özgü değildir; diğer enzimler ve klinik öykü olmadan kaynak belirlenemez.",
    relatedCodes: ["ALT", "ALP", "ALBUMIN"],
  },
  ALP: {
    subject: "Alkalen fosfataz",
    whatItIs: "ALP, özellikle safra yolları ve kemik dokusunda bulunan bir enzim grubudur.",
    bodyRole: "Fosfat gruplarının işlenmesine katılır; kemik mineralizasyonu ve safra sistemiyle ilişkili hücresel süreçlerde bulunur.",
    lowMeaning: "Düşük ALP; nadiren bazı beslenme yetersizlikleri, tiroid veya genetik durumlarla ilişkili olabilir; tek başına çoğu zaman özgül değildir.",
    highMeaning: "Yüksek ALP safra yolu/karaciğer kaynaklı veya kemik yapımının arttığı durumlarla ilişkili olabilir; yaş ve gebelik gibi fizyolojik etkenler de önemlidir.",
    whyOutOfRangeMatters: "ALP kaynağını ayırt etmek için diğer karaciğer testleri ve gerektiğinde kemik metabolizması göstergeleri değerlendirilir.",
    relatedCodes: ["ALT", "AST", "ALBUMIN"],
  },
  ALBUMIN: {
    subject: "Albümin",
    whatItIs: "Albümin, karaciğerde üretilen ve kandaki en bol plazma proteinlerinden biridir.",
    bodyRole: "Damar içindeki sıvı dengesinin korunmasına ve hormon, yağ asidi, ilaç gibi birçok maddenin taşınmasına katkı sağlar.",
    lowMeaning: "Düşük albümin; inflamasyon, karaciğer üretiminin azalması, böbrekten/protein kaybı, emilim sorunları veya yetersiz beslenme dahil birçok nedenle görülebilir.",
    highMeaning: "Yüksek albümin çoğunlukla sıvı kaybına bağlı kanın yoğunlaşmasıyla ilişkilidir.",
    whyOutOfRangeMatters: "Albümin beslenme durumundan etkilenebilir ancak tek başına beslenme yeterliliğinin doğrudan göstergesi değildir.",
    relatedCodes: ["ALT", "AST", "ALP", "CREATININE"],
  },
};

/** Returns detailed education only when the normalized biomarker is unambiguous. */
export function getBiomarkerDeepEducation(
  value: BloodTestNormalizedValue,
): BiomarkerDeepEducation | null {
  const code = value.biomarkerCode?.toUpperCase();

  // PCT is ambiguous in medicine. In a CBC, percentage PCT is plateletcrit;
  // another unit/context may represent procalcitonin and must not use this text.
  if (code === "PCT") {
    return value.unit.trim() === "%" ? DEEP.PCT : null;
  }

  return code ? DEEP[code] ?? null : null;
}
